<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_wooble</name>
   <tag></tag>
   <elementGuidId>ff7b6397-e058-4728-bd03-3852007e9f25</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wooble</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//n3.sdlcdn.com/imgs/f/b/6/large/Toshiba-Canvio-Ready-USB-3-SDL569944922-1-bfe7d.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ajaxWidget-products_c_widget_cmp-3&quot;)/div[@class=&quot;product-relative ceeProd dp-widget-link js-omni width20 favDp&quot;]/a[@class=&quot;product-card pp dp-widget-link&quot;]/div[@class=&quot;product-img&quot;]/img[@class=&quot;wooble&quot;]</value>
   </webElementProperties>
</WebElementEntity>
