<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_wooble</name>
   <tag></tag>
   <elementGuidId>fc02040d-bd6b-42df-88d4-dd4dd11b7ed4</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wooble</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://n3.sdlcdn.com/imgs/f/n/6/large/Mt_G_Black_Analog_Digital_SDL989102638_1_7f7f7-460b5.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ajaxWidget-products_c_widget_cxe-0&quot;)/div[@class=&quot;product-relative ceeProd dp-widget-link js-omni width20 favDp&quot;]/a[@class=&quot;product-card pp dp-widget-link&quot;]/div[@class=&quot;product-img&quot;]/img[@class=&quot;wooble&quot;]</value>
   </webElementProperties>
</WebElementEntity>
