<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_wooble</name>
   <tag></tag>
   <elementGuidId>5c69f5c7-7aa7-401a-924d-654120b7c161</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wooble</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://n3.sdlcdn.com/imgs/g/j/c/large/MFCURRENMETER1-40947.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ajaxWidget-products_c_widget_cxe-0&quot;)/div[@class=&quot;product-relative ceeProd dp-widget-link js-omni width20 favDp&quot;]/a[@class=&quot;product-card pp dp-widget-link&quot;]/div[@class=&quot;product-img&quot;]/img[@class=&quot;wooble&quot;]</value>
   </webElementProperties>
</WebElementEntity>
